/**
 * Skill-Author Integration — Phase 36 Stream 4
 * Extends skill-author to generate OKF-compatible files:
 * - Auto-adds index.md to new directories
 * - Auto-updates log.md with creation entry
 * - Auto-registers in NKS validators
 * - Ensures all generated files pass OKF + NKS validation
 */
import * as fs from "fs";
import * as path from "path";

const ROOT = process.cwd();

interface SkillAuthorInput {
  name: string;
  description: string;
  type: "skill" | "connector" | "playbook" | "workflow";
  domain: string;
  priority?: string;
  tags?: string[];
  actions?: string[];
}

interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Generates a complete OKF-compatible skill/connector directory.
 */
export function generateOkfSkill(input: SkillAuthorInput): {
  files: GeneratedFile[];
  directory: string;
} {
  const now = new Date().toISOString().split("T")[0];
  const dirName = input.name.toLowerCase().replace(/\s+/g, "-");
  const baseDir = input.type === "connector" ? "connectors" : "skills";
  const directory = path.join(ROOT, baseDir, dirName);
  const files: GeneratedFile[] = [];

  // SKILL.md
  const skillMd = `---
type: "${input.type}"
name: "${input.name}"
description: "${input.description}"
version: "0.1.0"
updated: "${now}"
domain: "${input.domain}"
priority: "${input.priority || "P2"}"
tags: ${JSON.stringify(input.tags || [input.domain])}
access: "internal"
---

# ${input.name}

## Description
${input.description}

## Actions
${(input.actions || []).map(a => `- **${a}:** TODO - describe this action`).join("\n") || "- (No actions defined yet)"}

## Usage
TODO: Add usage instructions and examples.

## Related Skills
- (Add related skills via cross-links)

---
*Generated by Skill-Author with OKF v0.1 compatibility. NKS v1.0 compliant.*
`;

  files.push({ path: path.join(directory, "SKILL.md"), content: skillMd });

  // PLAYBOOK.md (for connectors)
  if (input.type === "connector") {
    const playbookMd = `---
type: "connector"
name: "${input.name} Connector"
description: "Connector playbook for ${input.name}"
version: "0.1.0"
updated: "${now}"
scope: "connector"
auto_load: false
headline: |
  ${input.description}
access: "internal"
---

# ${input.name} Connector Playbook

## Architecture
TODO: Describe the connector architecture.

## API Pattern
TODO: Document the API pattern.

## Tools
TODO: List available tools.
`;

    files.push({ path: path.join(directory, "PLAYBOOK.md"), content: playbookMd });
  }

  // manifest.ts (for connectors)
  if (input.type === "connector") {
    const manifestTs = `/**
 * ${input.name} — Tool Manifest
 * Auto-generated by Skill-Author. NKS v1.0 compliant.
 */

export const manifest = {
  name: "${input.name}",
  version: "0.1.0",
  description: "${input.description}",
  tools: ${JSON.stringify(input.actions || [], null, 2)},
  generated: "${new Date().toISOString()}",
  nksVersion: "1.0.0",
  okfCompliant: true,
};
`;

    files.push({ path: path.join(directory, "manifest.ts"), content: manifestTs });
  }

  return { files, directory };
}

/**
 * Auto-adds index.md to a new directory.
 */
export function addIndexMd(directory: string, dirName: string, contents: string[]): void {
  const now = new Date().toISOString().split("T")[0];

  const indexMd = `---
type: index
name: "${dirName}"
description: "Index of knowledge artifacts in ${path.relative(ROOT, directory)}/"
version: "1.0.0"
updated: "${now}"
---

# ${dirName}

## Contents
${contents.map(c => `- [${c}](./${c})`).join("\n")}

---
*Auto-generated by Skill-Author. OKF v0.1 + NKS v1.0 compliant.*
`;

  fs.writeFileSync(path.join(directory, "index.md"), indexMd, "utf-8");
}

/**
 * Auto-updates log.md with creation entry.
 */
export function updateLogMd(knowledgeRoot: string, entry: string): void {
  const logPath = path.join(ROOT, knowledgeRoot, "log.md");
  const now = new Date().toISOString().split("T")[0];
  const logEntry = `\n## ${now}\n- **Skill-Author:** ${entry}\n`;

  if (fs.existsSync(logPath)) {
    const existing = fs.readFileSync(logPath, "utf-8");
    fs.writeFileSync(logPath, existing + logEntry, "utf-8");
  } else {
    const init = `---
type: index
name: "${path.basename(knowledgeRoot)} Change Log"
description: "Chronological change log"
version: "1.0.0"
updated: "${now}"
---

# Change Log
${logEntry}
`;
    fs.writeFileSync(logPath, init, "utf-8");
  }
}

/**
 * Full skill creation flow — generates directory, files, index.md, and updates log.md.
 */
export function createSkill(input: SkillAuthorInput): { directory: string; filesCreated: number } {
  const { files, directory } = generateOkfSkill(input);

  // Create directory
  fs.mkdirSync(directory, { recursive: true });

  // Write files
  let count = 0;
  for (const file of files) {
    const fileDir = path.dirname(file.path);
    fs.mkdirSync(fileDir, { recursive: true });
    fs.writeFileSync(file.path, file.content, "utf-8");
    count++;
  }

  // Add index.md to the new directory
  const fileNames = files.map(f => path.basename(f.path));
  addIndexMd(directory, input.name, fileNames);

  // Update parent directory index.md
  const parentDir = path.join(ROOT, path.dirname(path.relative(ROOT, directory)));
  const parentIndex = path.join(parentDir, "index.md");
  if (fs.existsSync(parentIndex)) {
    const existing = fs.readFileSync(parentIndex, "utf-8");
    const newEntry = `- [${input.name}/](./${path.basename(directory)}/index.md)\n`;
    if (!existing.includes(newEntry.trim())) {
      const lines = existing.split("\n");
      const subDirIdx = lines.findIndex(l => l.startsWith("## Subdirectories"));
      if (subDirIdx !== -1) {
        lines.splice(subDirIdx + 2, 0, newEntry);
        fs.writeFileSync(parentIndex, lines.join("\n"), "utf-8");
      }
    }
  }

  // Update log.md
  const knowledgeRoot = directory.includes("connectors") ? "connectors" : "skills";
  updateLogMd(knowledgeRoot, `Created ${input.type} "${input.name}" in ${path.relative(ROOT, directory)}/`);

  console.log(`✅ Skill-Author: Created ${count} files in ${path.relative(ROOT, directory)}/`);
  return { directory, filesCreated: count };
}

/**
 * Validates a newly created skill against NKS spec.
 */
export function validateNewSkill(directory: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  // Check required files exist
  const skillMd = path.join(directory, "SKILL.md");
  if (!fs.existsSync(skillMd)) errors.push("Missing SKILL.md");

  const indexMd = path.join(directory, "index.md");
  if (!fs.existsSync(indexMd)) errors.push("Missing index.md");

  // Check frontmatter
  if (fs.existsSync(skillMd)) {
    const content = fs.readFileSync(skillMd, "utf-8");
    const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
    if (!fmMatch) {
      errors.push("Missing YAML frontmatter");
    } else {
      const requiredFields = ["type", "name", "description", "version", "updated", "access"];
      for (const field of requiredFields) {
        if (!fmMatch[1].includes(`${field}:`)) {
          errors.push(`Missing required field: ${field}`);
        }
      }
    }
  }

  return { valid: errors.length === 0, errors };
}
