/**
 * POST /api/wizard/generate-skill — Generate SKILL.md, function wrappers, domain suggestions, or SOP.
 *
 * Body: {
 *   connectorName: string,
 *   apiUrl: string,
 *   endpoints: string[],
 *   mode: "skill" | "functions" | "domains" | "sop",
 *   mcpCheck?: { exists: boolean, url: string | null }
 * }
 *
 * Returns different payloads depending on mode:
 *   skill     → { skillContent: string }
 *   functions → { functions: { name, signature, description }[] }
 *   domains   → { domains: string[] }
 *   sop       → { sopContent: string }
 */

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";

const bodySchema = z.object({
  connectorName: z.string().min(1),
  apiUrl: z.string().url(),
  endpoints: z.array(z.string()).default([]),
  mode: z.enum(["skill", "functions", "domains", "sop"]).default("skill"),
  mcpCheck: z.object({ exists: z.boolean(), url: z.string().nullable() }).optional(),
});

export async function POST(request: NextRequest) {
  let body: z.infer<typeof bodySchema>;
  try {
    body = bodySchema.parse(await request.json());
  } catch {
    return NextResponse.json({ error: "Invalid body" }, { status: 400 });
  }

  const { connectorName, apiUrl, endpoints, mode, mcpCheck } = body;
  const domain = new URL(apiUrl).hostname.replace(/^api\./, "").replace(/\.com$/, "").replace(/\./g, "-");

  switch (mode) {
    case "skill":
      return NextResponse.json({ skillContent: generateSkillMd(connectorName, apiUrl, endpoints, domain, mcpCheck) });
    case "functions":
      return NextResponse.json({ functions: generateFunctions(connectorName, apiUrl, endpoints) });
    case "domains":
      return NextResponse.json({ domains: suggestDomains(connectorName, domain, endpoints) });
    case "sop":
      return NextResponse.json({ sopContent: generateSop(connectorName, apiUrl, endpoints, domain) });
  }
}

// ── Skill Generator ───────────────────────────────────────────────────────

function generateSkillMd(
  name: string,
  apiUrl: string,
  endpoints: string[],
  domain: string,
  mcpCheck?: { exists: boolean; url: string | null },
): string {
  const now = new Date().toISOString();
  return `---
skill: ${name}
version: "1.0.0"
domain: ${domain}
scope: connector
connector: ${name}
auto_load: true
headline: "Integration with ${new URL(apiUrl).hostname} API"
priority: P2
${mcpCheck?.exists ? `mcp_server: "${mcpCheck.url ?? 'smithery.ai'}"` : "mcp_enabled: false"}
triggers:
  - ${domain}
  - ${name.replace(/-connector$/, "").replace(/-/g, " ")}
endpoints:
${endpoints.slice(0, 10).map((e) => `  - ${e}`).join("\n")}
---

# ${name} — Integration Skill

## Pre-Check Knowledge
Before executing, query the Knowledge Graph:
- \`knowledge://${domain}/cardinal-rules\`
- \`knowledge://${domain}/rate-limits\`

## Operational Context
- **API Base:** ${apiUrl}
- **Connector Name:** ${name}
- **Domain:** ${domain}
- **MCP Status:** ${mcpCheck?.exists ? "Existing MCP server found" : "No existing MCP server"}
${mcpCheck?.url ? `- **MCP URL:** ${mcpCheck.url}` : ""}

## Available Endpoints
${endpoints.map((e) => `- \`${e}\``).join("\n")}

## Cardinal Rules
1. Always check rate limits before calling
2. Cache responses where possible (ETag/If-None-Match)
3. Handle 429 gracefully with exponential backoff
4. Log all API calls to library_model_usage_logs

## Anti-Patterns
- DON'T call the API without checking auth
- DON'T retry on 4xx errors
- DON'T assume pagination structure — always check response headers

## Constraints
- \`context_tokens_estimated\`: 2000
- \`typical_latency_ms\`: ${endpoints.length > 0 ? "500" : "1000"}
- \`dependencies\`: []
- \`optimal_for\`: ["api integration", "data fetching"]
- \`suboptimal_for\`: ["real-time streaming"]

## Self-Healing Rules
- On 401: refresh auth token
- On 429: wait Retry-After seconds
- On 5xx: exponential backoff (1s, 2s, 4s, 8s)
- On timeout: reduce batch size

---
Generated by Custom Connector Wizard at ${now}
`;
}

// ── Function Generator ────────────────────────────────────────────────────

function generateFunctions(
  name: string,
  _apiUrl: string,
  endpoints: string[],
): { name: string; signature: string; description: string }[] {
  const connectorPascal = name
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");

  const functions: { name: string; signature: string; description: string }[] = [];

  // Auth function
  functions.push({
    name: `${connectorPascal}Auth`,
    signature: `async function ${connectorPascal}Auth(apiKey: string): Promise<{ token: string; expiresAt: Date }>`,
    description: `Authenticate with ${name} API and return a bearer token`,
  });

  // Generate functions from endpoints
  for (const ep of endpoints.slice(0, 12)) {
    const cleanPath = ep
      .replace(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS)\s+/i, "")
      .replace(/[\/{}]/g, "_")
      .replace(/^_/, "")
      .replace(/_+/g, "_")
      .replace(/_$/, "")
      .replace(/[^a-zA-Z0-9_]/g, "_");

    const methodMatch = ep.match(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS)/i);
    const method = methodMatch ? methodMatch[1].toUpperCase() : "GET";

    const fnName = `${connectorPascal}_${cleanPath || "root"}`;
    const hasParam = ep.includes("{");

    if (method === "GET") {
      functions.push({
        name: fnName,
        signature: `async function ${fnName}(params?: Record<string, unknown>): Promise<Record<string, unknown>>`,
        description: `GET request to ${ep.replace(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS)\s+/i, "").trim()}`,
      });
    } else if (method === "POST") {
      functions.push({
        name: fnName,
        signature: `async function ${fnName}(data: Record<string, unknown>): Promise<Record<string, unknown>>`,
        description: `POST request to ${ep.replace(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS)\s+/i, "").trim()}`,
      });
    } else {
      functions.push({
        name: fnName,
        signature: `async function ${fnName}(${hasParam ? "id: string, " : ""}data?: Record<string, unknown>): Promise<Record<string, unknown>>`,
        description: `${method} request to ${ep.replace(/^(GET|POST|PUT|PATCH|DELETE|OPTIONS)\s+/i, "").trim()}`,
      });
    }
  }

  return functions.slice(0, 20);
}

// ── Domain Suggester ──────────────────────────────────────────────────────

function suggestDomains(
  _name: string,
  domain: string,
  endpoints: string[],
): string[] {
  const domains = new Set<string>();
  const endpointText = endpoints.join(" ").toLowerCase();
  const allText = `${domain} ${endpointText}`;

  // Keyword-based domain matching
  const domainKeywords: Record<string, RegExp[]> = {
    "billing-flow": [/billing|payment|charge|refund|invoice|transaction|subscription/],
    "credit-disputes": [/dispute|credit|debt|fcra|report/],
    "customer-enrollment": [/enroll|customer|signup|register|onboard/],
    "support-triage": [/ticket|support|help|escalate|complaint/],
    "agent-payments": [/payment|payout|commission|earning/],
    "customer-comms": [/email|sms|message|notif|communication|slack/],
    "lead-flow": [/lead|prospect|marketing|campaign/],
    "mcp-edits": [/code|edit|deploy|commit|pr/],
    engineering: [/code|api|dev|engineering|build/],
    reporting: [/report|analytics|metrics|dashboard|stats/],
    "vps-ops": [/vps|server|deploy|nginx|dns/],
  };

  for (const [dom, patterns] of Object.entries(domainKeywords)) {
    if (patterns.some((p) => p.test(allText))) {
      domains.add(dom);
    }
  }

  // Always suggest the domain derived from the API hostname
  domains.add(domain);

  // Fallback if nothing matched
  if (domains.size <= 1) {
    domains.add("mcp-edits");
    domains.add("engineering");
  }

  return [...domains].slice(0, 6);
}

// ── SOP Generator ─────────────────────────────────────────────────────────

function generateSop(
  name: string,
  apiUrl: string,
  endpoints: string[],
  domain: string,
): string {
  const hostname = new URL(apiUrl).hostname;
  return `# ${name} — Standard Operating Procedure

## Overview
This SOP covers all operations involving the ${hostname} API through the ${name} connector. Follow these procedures for consistent, reliable integration.

## Prerequisites
- Valid API credentials for ${hostname}
- Connector configured in Neptune Chat
- Network access to ${apiUrl}

## Common Operations

### Authentication
1. Obtain API key/token from ${hostname} dashboard
2. Store securely in Neptune Vault (\`vault set ${name}_api_key\`)
3. Connector auto-refreshes tokens before expiry

### Rate Limits
- **Default tier:** 100 requests/minute
- **Burst:** 10 concurrent requests
- **Daily cap:** 10,000 requests
- Always check response headers: \`X-RateLimit-Remaining\`, \`X-RateLimit-Reset\`

### Available Endpoints
${endpoints.slice(0, 15).map((e, i) => `${i + 1}. \`${e}\``).join("\n")}

## Anti-Patterns (DO NOT DO)
1. **DON'T call endpoints without checking auth status** — always verify token validity first
2. **DON'T retry on 4xx errors** — fix the request, don't hammer the API
3. **DON'T assume pagination structure** — always read Link/Content-Range headers
4. **DON'T hardcode URLs** — use the connector registry for base URL resolution
5. **DON'T cache sensitive data** — PII and payment data must never be cached

## Error Recovery
| Error | Action |
|-------|--------|
| 401 Unauthorized | Refresh token via ${connectorPascal(name)}Auth |
| 429 Rate Limited | Wait Retry-After seconds, reduce concurrency |
| 5xx Server Error | Exponential backoff (1s, 2s, 4s, 8s), max 3 retries |
| Timeout (>30s) | Reduce batch size, retry once |
| Network Error | Circuit break for 60s, notify #jarvis-admin |

## Monitoring
- Log all calls to \`library_model_usage_logs\`
- Alert on >5% error rate in any 5-minute window
- Weekly cost audit via \`/api/library/model-usage\`

---
Generated by Custom Connector Wizard · ${new Date().toISOString()}
`;
}

function connectorPascal(name: string): string {
  return name.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}
