/**
 * create-playbook.ts — Scaffold a new playbook in the fractal library.
 *
 * Creates a new playbook .md file with YAML frontmatter, domain routing config,
 * and SOP template sections. Validates against existing playbooks to prevent
 * duplicates. Part of the playbook-skills meta-skill.
 */

import { existsSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";

export interface CreatePlaybookInput {
  /** Short domain name (e.g., "compliance", "onboarding") */
  domain: string;
  /** Display title */
  title: string;
  /** Priority tier */
  priority: "P0" | "P1" | "P2";
  /** Brief description */
  description: string;
  /** Default model routing config */
  modelRouting?: {
    default?: string;
    reasoning_heavy?: string;
    fast_iteration?: string;
    coding?: string;
    long_context?: string;
  };
}

export interface CreatePlaybookResult {
  success: boolean;
  path: string;
  domain: string;
  message: string;
  alreadyExists?: boolean;
}

const PLAYBOOKS_DIR = join(
  process.cwd(),
  "connectors/neptune/skills/custom-skills/playbook-skills/playbooks"
);

function generateFrontmatter(input: CreatePlaybookInput): string {
  const date = new Date().toISOString().split("T")[0];
  const modelRouting = input.modelRouting ?? {
    default: "deepseek/deepseek-v4-pro",
    reasoning_heavy: "anthropic/claude-sonnet-4-6",
    fast_iteration: "deepseek/deepseek-v4-flash",
  };

  return [
    "---",
    `title: "${input.title}"`,
    `domain: ${input.domain}`,
    `priority: ${input.priority}`,
    `version: "1.0.0"`,
    `date: ${date}`,
    `status: ACTIVE`,
    `description: "${input.description}"`,
    "model_routing:",
    `  default: "${modelRouting.default}"`,
    ...(modelRouting.reasoning_heavy ? [`  reasoning_heavy: "${modelRouting.reasoning_heavy}"`] : []),
    ...(modelRouting.fast_iteration ? [`  fast_iteration: "${modelRouting.fast_iteration}"`] : []),
    ...(modelRouting.coding ? [`  coding: "${modelRouting.coding}"`] : []),
    ...(modelRouting.long_context ? [`  long_context: "${modelRouting.long_context}"`] : []),
    "---",
    "",
  ].join("\n");
}

function generateTemplate(input: CreatePlaybookInput): string {
  return [
    `# ${input.title}`,
    "",
    `> **Domain:** ${input.domain} | **Priority:** ${input.priority} | **Version:** 1.0.0`,
    `> **Canonical path:** \`connectors/neptune/skills/custom-skills/playbook-skills/playbooks/playbook-${input.domain}.md\``,
    "",
    "## Domain Scope",
    "",
    input.description,
    "",
    "## Intent Routing",
    "",
    "| Intent | Trigger Keywords | Action |",
    "|--------|-----------------|--------|",
    `| Primary | <keywords> | Describe the primary action |`,
    "",
    "## Connectors",
    "",
    "- `connectors/<name>/` — Purpose",
    "",
    "## Safeguards",
    "",
    "1. **Safeguard 1** — description",
    "2. **Safeguard 2** — description",
    "",
    "## Anti-Patterns",
    "",
    "- ❌ Anti-pattern 1 — why wrong",
    "- ❌ Anti-pattern 2 — why wrong",
    "",
    "## SOP Workflow",
    "",
    "1. **Step 1:** Validate preconditions",
    "2. **Step 2:** Execute primary action",
    "3. **Step 3:** Verify outcome",
    "4. **Step 4:** Annotate back to playbook",
    "",
    "---",
    "",
    `*Generated by playbook-skills create-playbook function on ${new Date().toISOString()}.*`,
  ].join("\n");
}

/**
 * Create a new playbook in the fractal library.
 * Returns error if a playbook with the same domain already exists.
 */
export function createPlaybook(input: CreatePlaybookInput): CreatePlaybookResult {
  const filename = `playbook-${input.domain}.md`;
  const filePath = join(PLAYBOOKS_DIR, filename);

  // Check for duplicates
  if (existsSync(filePath)) {
    return {
      success: false,
      path: filePath,
      domain: input.domain,
      message: `Playbook "${filename}" already exists. Use update-playbook to modify it.`,
      alreadyExists: true,
    };
  }

  // Also check for similar names
  try {
    const existing = readdirSync(PLAYBOOKS_DIR);
    const similar = existing.find((f) => f.includes(input.domain));
    if (similar) {
      return {
        success: false,
        path: join(PLAYBOOKS_DIR, similar),
        domain: input.domain,
        message: `Similar playbook "${similar}" already exists. Consider extending it instead.`,
        alreadyExists: true,
      };
    }
  } catch {
    // Directory might not exist — that's OK, we'll create the file
  }

  // Generate and write
  const frontmatter = generateFrontmatter(input);
  const template = generateTemplate(input);
  const content = frontmatter + template;

  try {
    writeFileSync(filePath, content, "utf-8");
    return {
      success: true,
      path: filePath,
      domain: input.domain,
      message: `Created new playbook: ${filename} (${input.priority})`,
    };
  } catch (err) {
    return {
      success: false,
      path: filePath,
      domain: input.domain,
      message: `Failed to write playbook: ${err instanceof Error ? err.message : "Unknown error"}`,
    };
  }
}

export default createPlaybook;
