import { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Check, Minus, X } from "lucide-react";

export const metadata: Metadata = { title: "OKF Compatibility — NKS v1.0" };

export default function CompatibilityPage() {
  const rows = [
    { feature: "index.md per directory", okf: true, nks: true, notes: "Identical" },
    { feature: "log.md (change log)", okf: "recommended", nks: true, notes: "NKS adds structured entries" },
    { feature: "type field (YAML)", okf: true, nks: true, notes: "NKS adds 10 new type values" },
    { feature: "name / description / version", okf: true, nks: true, notes: "Identical" },
    { feature: "updated (ISO 8601)", okf: true, nks: true, notes: "Identical" },
    { feature: "tags array", okf: "optional", nks: "optional", notes: "Identical" },
    { feature: "links array", okf: "optional", nks: "recommended", notes: "NKS encourages cross-links" },
    { feature: "relative markdown links", okf: true, nks: true, notes: "Identical" },
    { feature: "manifest.yaml", okf: "optional", nks: "built-in", notes: "Auto-generated by export tool" },
    { feature: "access field (RBAC)", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Playbook routing", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Agent skill definitions", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Mission state machines", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Memory references", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Connector specs", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "UI component binding", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Workflow orchestration", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Self-coding", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Audit trails", okf: false, nks: true, notes: "NKS innovation" },
    { feature: "Knowledge graph", okf: false, nks: true, notes: "NKS innovation" },
  ];

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <Link href="/spec" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground mb-6">
          <ArrowLeft size={12} /> Back to Spec
        </Link>
        <h1 className="text-3xl font-bold mb-2">OKF v0.1 Compatibility Matrix</h1>
        <p className="text-muted-foreground mb-8">Every NKS feature is additive. Nothing is removed or renamed.</p>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b">
                <th className="text-left py-2 font-medium">Feature</th>
                <th className="text-center py-2 font-medium w-20">OKF v0.1</th>
                <th className="text-center py-2 font-medium w-20">NKS v1.0</th>
                <th className="text-left py-2 font-medium">Notes</th>
              </tr>
            </thead>
            <tbody>
              {rows.map(row => (
                <tr key={row.feature} className="border-b last:border-0 hover:bg-muted/30">
                  <td className="py-2">{row.feature}</td>
                  <td className="text-center py-2">
                    {row.okf === true ? <Check size={14} className="inline text-emerald-500" /> :
                     row.okf === false ? <X size={14} className="inline text-red-400" /> :
                     <Minus size={14} className="inline text-amber-400" />}
                  </td>
                  <td className="text-center py-2">
                    {row.nks === true ? <Check size={14} className="inline text-emerald-500" /> :
                     row.nks === false ? <X size={14} className="inline text-red-400" /> :
                     <Minus size={14} className="inline text-amber-400" />}
                  </td>
                  <td className="py-2 text-muted-foreground text-xs">{row.notes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
