/**
 * Phase 24B: Connector Skills Generator
 *
 * Reads lib/ai/tools/* for connector-specific tools,
 * auto-generates skill.md + functions.yaml per connector if missing.
 *
 * Usage: npx tsx scripts/generate-connector-skills.ts [--dry-run]
 */

import { readdirSync, readFileSync, existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = join(__dirname, "..");
const TOOLS_DIR = join(REPO_ROOT, "lib", "ai", "tools");
const CONNECTOR_SKILLS_DIR = join(
  REPO_ROOT,
  "connectors/neptune/skills/custom-skills/playbook-skills/connector-skills"
);

// ── Connector → tool mapping ────────────────────────────────────────────

const CONNECTOR_TOOL_PATTERNS: Record<string, { pattern: RegExp; connector: string }> = {
  nmi: { pattern: /nmi/i, connector: "nmi" },
  slack: { pattern: /slack/i, connector: "slack" },
  ghl: { pattern: /ghl|gohighlevel/i, connector: "ghl" },
  base44: { pattern: /base44|b44_|entity_|cross_system/i, connector: "base44" },
  vapi: { pattern: /vapi/i, connector: "vapi" },
  hyperswitch: { pattern: /hyperswitch/i, connector: "hyperswitch" },
  freshcaller: { pattern: /freshcaller/i, connector: "freshcaller" },
  forth: { pattern: /forth|dpp/i, connector: "forth-dpp" },
  github: { pattern: /github|gh_|pr_/i, connector: "github" },
  vercel: { pattern: /vercel|deploy_/i, connector: "vercel" },
  hostinger: { pattern: /hostinger|vps_|nginx|pm2|ssh_/i, connector: "hostinger-vps" },
  resend: { pattern: /resend|email_/i, connector: "resend" },
};

// ── Main ──────────────────────────────────────────────────────────────────

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  console.log("🔍 Scanning tools for connector patterns...\n");

  if (!existsSync(TOOLS_DIR)) {
    console.error(`❌ Tools directory not found: ${TOOLS_DIR}`);
    process.exit(1);
  }

  const toolFiles = readdirSync(TOOLS_DIR).filter((f) => f.endsWith(".ts") || f.endsWith(".tsx"));
  const connectorTools: Record<string, string[]> = {};

  for (const file of toolFiles) {
    const content = readFileSync(join(TOOLS_DIR, file), "utf-8");
    for (const [key, { pattern }] of Object.entries(CONNECTOR_TOOL_PATTERNS)) {
      if (pattern.test(content) || pattern.test(file)) {
        if (!connectorTools[key]) connectorTools[key] = [];
        connectorTools[key].push(file.replace(/\.(ts|tsx)$/, ""));
      }
    }
  }

  for (const [connector, tools] of Object.entries(connectorTools)) {
    const dir = join(CONNECTOR_SKILLS_DIR, connector);
    if (!existsSync(dir)) {
      if (!dryRun) mkdirSync(dir, { recursive: true });
      console.log(`📁 Created: ${connector}/`);
    }

    // Generate functions.yaml if missing
    const functionsPath = join(dir, "functions.yaml");
    if (!existsSync(functionsPath)) {
      const yaml = [
        "functions:",
        ...tools.map((t) => `  - name: ${t}`),
        ...tools.map((t) => `    description: Auto-detected from lib/ai/tools/${t}.ts`),
        "",
      ].join("\n");
      if (!dryRun) writeFileSync(functionsPath, yaml);
      console.log(`  ✅ functions.yaml (${tools.length} tools: ${tools.join(", ")})`);
    } else {
      console.log(`  ⏭️  functions.yaml exists (${tools.length} tools detected: ${tools.join(", ")})`);
    }

    // Generate skill.md if missing
    const skillPath = join(dir, "skill.md");
    if (!existsSync(skillPath)) {
      const md = [
        `# ${connector} Connector Skill`,
        "",
        "## What It Does",
        "Auto-generated connector skill for " + connector + ".",
        "",
        "## Available Tools",
        ...tools.map((t) => `- \`${t}\``),
        "",
        "## Auto-Generated",
        `This file was auto-generated by scripts/generate-connector-skills.ts.`,
        "Update it with connector-specific documentation.",
        "",
      ].join("\n");
      if (!dryRun) writeFileSync(skillPath, md);
      console.log(`  ✅ skill.md`);
    } else {
      console.log(`  ⏭️  skill.md exists`);
    }
  }

  // Report connectors with no detected tools
  const existingConnectors = readdirSync(CONNECTOR_SKILLS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name);
  const withoutTools = existingConnectors.filter((c) => !connectorTools[c]);
  if (withoutTools.length > 0) {
    console.log(`\n⚠️  Connectors with no detected tools: ${withoutTools.join(", ")}`);
    console.log("   These may need manual function definitions.");
  }

  console.log(`\n${dryRun ? "🔍 Dry run" : "✅ Generation"} complete!`);
}

main().catch(console.error);
